import './globals.css';
import { Providers } from './GlobalRedux/provider';
import ProtectedRoute from '../components/ProtectedRoute';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <ProtectedRoute>
            {children}
          </ProtectedRoute>
          </Providers>
      </body>
    </html>
  );
}
